# eventing-in-memory-channel-dispatcher
# 1.13.3
#FROM gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_dispatcher@sha256:4562f1cedf30783f5aff60794c0ed58afc6abaca98a79d7635e100164ad7395e

#1.14.1
FROM gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_dispatcher@sha256:e017adf74e7f445acb86c7c6ff266b20497b6c5bcf5d17f5fb48f3ec145310ea
