# 1.13.3
#FROM gcr.io/knative-releases/knative.dev/eventing-kafka-broker/control-plane/cmd/kafka-controller@sha256:fda50dbcb9babba3f32202315f920fde8b569022d8758934351281ef8a74ca52

# 1.14.4
FROM gcr.io/knative-releases/knative.dev/eventing-kafka-broker/control-plane/cmd/kafka-controller@sha256:3e4c87bdc5c7ba63a50aa5dfb2765424e0d42aa4da22846482af171a5dcccad6
